dotenv: .env
networks:
  default: development
  rinkeby:
    verify: True
  mainnet-fork:
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
  bdltestnet:
    verify: False
wallets:
  account1: ${PRIVATE_KEY1}
  account2: ${PRIVATE_KEY2}
  account3: ${PRIVATE_KEY3}
  account4: ${PRIVATE_KEY4}
  account5: ${PRIVATE_KEY5}